const AUTH_SERVICES_BASE_URL = `${process.env.REACT_APP_HIVEPATH_AUTH_API_URL}`;
const LANDING_PAGE_SERVICES_BASE_URL = `${process.env.REACT_APP_HIVEPATH_LANDING_PAGE_API_URL}`;
const KNOWLEDGE_SESSIONS_SERVICES_BASE_URL = `${process.env.REACT_APP_HIVEPATH_KNOWLEDGE_SESSION_API_URL}`;
const USER_PROFILE_SERVICES_BASE_URL = `${process.env.REACT_APP_HIVEPATH_USER_PROFILE_API_URL}`;
const CALENDAR_SERVICES_BASE_URL = `${process.env.REACT_APP_HIVEPATH_CALENDAR_API_URL}`;
const SCHEDULE_SERVICES_BASE_URL = `${process.env.REACT_APP_HIVEPATH_SCHEDULE_API_URL}`;

const HIVEPATH_API_URLS = {
  AUTH_SERVICES: {
    SEND_VERIFICATION_EMAIL: `${AUTH_SERVICES_BASE_URL}/sendVerification`,
    LOGIN: `${AUTH_SERVICES_BASE_URL}/login`,
    LOGOUT: `${AUTH_SERVICES_BASE_URL}/logout`,
    CHECK_USER_EXIST: `${AUTH_SERVICES_BASE_URL}/checkUserExist`,
    REGISTRATION: `${AUTH_SERVICES_BASE_URL}/registration`,
    TEST_REGISTRATION: `${AUTH_SERVICES_BASE_URL}/testRegistration`,
    FORGOT_PASSWORD: `${AUTH_SERVICES_BASE_URL}/forgotPassword`,
    RESET_PASSWORD: `${AUTH_SERVICES_BASE_URL}/resetPassword`,
    RESET_PASSWORD_FROM_PROFILE: `${AUTH_SERVICES_BASE_URL}/resetPasswordProfile`,
    VERIFY_REGISTER: `${AUTH_SERVICES_BASE_URL}/verifyRegister`,
    VERIFY_RESET_PASSWORD_TOKEN: `${AUTH_SERVICES_BASE_URL}/verifyResetPasswordToken`,
    VERIFY_LOGIN_TOKEN: `${AUTH_SERVICES_BASE_URL}/verifyLoginToken`,
    GOOGLE_LOGIN: `${AUTH_SERVICES_BASE_URL}/GoogleLogin`,
    GOOGLE_LOGIN_AUTHORIZE: `${AUTH_SERVICES_BASE_URL}/GoogleLogin/authorize`,
    LINKEDIN_LOGIN: `${AUTH_SERVICES_BASE_URL}/LinkedinLogin`,
    LINKEDIN_LOGIN_AUTHORIZE: `${AUTH_SERVICES_BASE_URL}/LinkedinLogin/authorize`,
    FACEBOOK_LOGIN: `${AUTH_SERVICES_BASE_URL}/FacebookLogin`,
    FACEBOOK_LOGIN_AUTHORIZE: `${AUTH_SERVICES_BASE_URL}/FacebookLogin/authorize`,
    SSO_AUTH: `${AUTH_SERVICES_BASE_URL}/ssoAuth`,
    LINKEDIN_SSO_AUTH: `${AUTH_SERVICES_BASE_URL}/linkedinssoAuth`,
    CREATE_ZOOM_MEETING: `${AUTH_SERVICES_BASE_URL}/createZoomMeeting`,
    AUTHORIZE_ZOOM: `${AUTH_SERVICES_BASE_URL}/authorizeZoom`,
    SAVE_ZOOM_SECRET: `${AUTH_SERVICES_BASE_URL}/saveZoomSecret`,
    AUTHORIZE_GOOGLE: `${AUTH_SERVICES_BASE_URL}/authorizegoogle`,
    FETCH_MY_ATTENDEES: `${AUTH_SERVICES_BASE_URL}/fetchMyAttendees`,
    FETCH_MY_HOSTS: `${AUTH_SERVICES_BASE_URL}/fetchMyHosts`,
    FETCH_ALL_HOST_SESSIONS: `${AUTH_SERVICES_BASE_URL}/fetchAllHostSessions`,
    SHARE_REFERRAL_VIA_LINKEDIN: `${AUTH_SERVICES_BASE_URL}/sharereferralvialinkedin`,
    SHARE_REFERRAL_VIA_FACEBOOK: `${AUTH_SERVICES_BASE_URL}/sharereferralviafacebook`,
    SHARE_REFERRAL_VIA_TWITTER: `${AUTH_SERVICES_BASE_URL}/sharereferralviatwitter`,
    AUTHORIZE_TWITTER: `${AUTH_SERVICES_BASE_URL}/authorizetwitter`,
    SYNC_MEET_ACCOUNT: `${AUTH_SERVICES_BASE_URL}/syncMeetAccount`,
    CREATE_GMEET: `${AUTH_SERVICES_BASE_URL}/createGmeet`,
    FETCH_MEET_ACCOUNTS: `${AUTH_SERVICES_BASE_URL}/fetchMeetAccounts`,
    ADD_MEET_ACCOUNT: `${AUTH_SERVICES_BASE_URL}/addMeetAccounts`,
    DELETE_MEET_ACCOUNT: `${AUTH_SERVICES_BASE_URL}/deleteMeetAccount`,
    DELETE_GMEET: `${AUTH_SERVICES_BASE_URL}/deleteGmeet`,
    TEST_NEW_MAIL: `${AUTH_SERVICES_BASE_URL}/testNewMail`,
  },
  LANDING_PAGE_SERVICES: {
    FETCH_ALL_UPCOMING_SESSIONS: `${LANDING_PAGE_SERVICES_BASE_URL}/fetchAllUpcomingSessions`,
    FETCH_ALL_OTHER_OFFERINGS: `${LANDING_PAGE_SERVICES_BASE_URL}/fetchAllOthersOfferings`,

    FETCH_ALL_OTHER_PROFILES: `${LANDING_PAGE_SERVICES_BASE_URL}/fetchAllOthersProfiles`,

    FETCH_RECOMMENDED_OFFERINGS: `${LANDING_PAGE_SERVICES_BASE_URL}/recommendedOfferings`,

    FETCH_RECOMMNEDED_HOSTS: `${LANDING_PAGE_SERVICES_BASE_URL}/recommendedHosts`,

    FILTERED_OFFERINGS: `${LANDING_PAGE_SERVICES_BASE_URL}/filteredOfferings`,
  },
  KNOWLEDGE_SESSIONS_SERVICES: {
    FETCH_USER_OFFERING: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/fetchUserOffering`,

    FETCH_ALL_USER_OFFERING: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/fetchUserOffering`,
    CREATE_USER_OFFERING: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/userOffering`,
    UPDATE_USER_OFFERING: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/updateUserOffering`,
    DELETE_USER_OFFERING: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/deleteUserOffering`,
    FETCH_SESSION_SUGGESTIONS: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/fetchSessionSuggestions`,

    FETCH_SESSION_CATEGORIES: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/fetchSessionCategories`,

    ADD_SESSION_PREFERENCES: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/sessionPreferences`,
    FETCH_PREFERENCES: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/fetchPreferences`,
    UPDATE_PREFERENCES: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/updatePreferences`,
    DELETE_PREFERENCES: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/ deletePreferences`,

    SUBMIT_OFFERING_ONBOARDING: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/submitOfferingOnboarding`,

    FETCH_SESSION_ONBOARDING: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/fetchSessionOnboarding`,

    CREATE_BOOKMARK: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/createBookmark`,
    UPDATE_BOOKMARK: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/updateBookmark`,
    CREATE_DEFAULT_BOOKMARK: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/createDefaultBookmark`,
    FETCH_BOOKMARKs: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/fetchBookmarks`,
    DELETE_BOOKMARK: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/deleteBookmark`,
    BOOKMARK_A_SESSION: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/bookmarkSession`,
    UNBOOKMARK_A_SESSION: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/unbookmarkSession`,
    SHOW_BOOKMARKED_SESSIONS: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/showMyBookmarkedSessions`,

    FETCH_SESSION_DOCUMENTS: `${KNOWLEDGE_SESSIONS_SERVICES_BASE_URL}/fetchSessionDocuments`,
  },
  USER_PROFILE_SERVICES: {
    CREATE_USER_PROFILE: `${USER_PROFILE_SERVICES_BASE_URL}/userProfile`,
    FETCH_USER_PROFILE: `${USER_PROFILE_SERVICES_BASE_URL}/fetchUserProfile`,
    FETCH_USER_DATA: `${USER_PROFILE_SERVICES_BASE_URL}/fetchUserData`,
    UPDATE_USER_PROFILE: `${USER_PROFILE_SERVICES_BASE_URL}/updateUserProfile`,
    DELETE_USER_PROFILE: `${USER_PROFILE_SERVICES_BASE_URL}/deleteUserProfile`,
    SUBMIT_PROFILE_ONBOARDING: `${USER_PROFILE_SERVICES_BASE_URL}/submitProfileOnboarding`,
    FETCH_PROFILE_ONBOARDING_STATUS: `${USER_PROFILE_SERVICES_BASE_URL}/fetchProfileOnboardingStatus`,
    FETCH_PUBLIC_USER_PROFILE: `${USER_PROFILE_SERVICES_BASE_URL}/publicFetchUserProfile`,
    FETCH_SLUG_URL: `${USER_PROFILE_SERVICES_BASE_URL}/fetchSlugURL`,
    SLUG_FETCH_USER_PROFILE: `${USER_PROFILE_SERVICES_BASE_URL}/slugFetchUserProfile`,
    CREATE_USER_ONBOARDING: `${USER_PROFILE_SERVICES_BASE_URL}/userOnboarding`,
    FETCH_USER_ONBOARDING: `${USER_PROFILE_SERVICES_BASE_URL}/fetchUserOnboarding`,
    CHECK_SLUG: `${USER_PROFILE_SERVICES_BASE_URL}/checkSlug`,
    USER_PROFILE_ONBOARDING: `${USER_PROFILE_SERVICES_BASE_URL}/userProfileOnboarding`,
    FOLLOW_USER: `${USER_PROFILE_SERVICES_BASE_URL}/followUser`,
    UNFOLLOW_USER: `${USER_PROFILE_SERVICES_BASE_URL}/unfollowUser`,
    LIST_FOLLOWERS: `${USER_PROFILE_SERVICES_BASE_URL}/listFollowers`,
    LIST_FOLLOWING: `${USER_PROFILE_SERVICES_BASE_URL}/listFollowing`,
    BOOKMARK_PROFILE: `${USER_PROFILE_SERVICES_BASE_URL}/bookmarkProfile`,
    SHOW_MY_BOOKMARKED_PROFILES: `${USER_PROFILE_SERVICES_BASE_URL}/showMyBookmarkedProfiles`,
    UNBOOKMARK_PROFILE: `${USER_PROFILE_SERVICES_BASE_URL}/unbookmarkProfile`,
    CREATE_PUBLIC_REFERRAL_LINK: `${USER_PROFILE_SERVICES_BASE_URL}/createPublicReferalLink`,
    FETCH_REFERRAL_HISTORY: `${USER_PROFILE_SERVICES_BASE_URL}/fetchReferralHistory`,
    SHARE_REFERRAL_VIA_EMAIL: `${USER_PROFILE_SERVICES_BASE_URL}/sharereferralviaemail`,
  },
  CALENDAR_SERVICES: {
    CREATE_SLOT_PLAN: `${CALENDAR_SERVICES_BASE_URL}/slotPlan`,

    FETCH_SLOT_PLAN: `${CALENDAR_SERVICES_BASE_URL}/fetchSlotPlan`,
    DELETE_SLOT_PLAN: `${CALENDAR_SERVICES_BASE_URL}/deleteSlotPlan`,
    FETCH_SYNCED_CALENDAR: `${CALENDAR_SERVICES_BASE_URL}/fetchSyncedCalendar`,
    SYNC_CALENDAR_ACCOUNT: `${CALENDAR_SERVICES_BASE_URL}/syncCalendarAccount`,
    RESYNC_CALENDAR_ACCOUNT: `${CALENDAR_SERVICES_BASE_URL}/reSyncCalendarAccount`,
    DESYNC_CALENDAR_ACCOUNT: `${CALENDAR_SERVICES_BASE_URL}/deSyncCalendarAccount`,
    ADD_CALENDAR_ACCOUNT: `${CALENDAR_SERVICES_BASE_URL}/addCalendarAccount`,
    FETCH_CALENDAR_VIEW: `${CALENDAR_SERVICES_BASE_URL}/fetchCalendarView`,
    FETCH_SLOTS: `${CALENDAR_SERVICES_BASE_URL}/fetchSlots`,
    FETCH_LATEST_AVAILABLE_SLOTS: `${CALENDAR_SERVICES_BASE_URL}/fetchLatestAvailableSlots`,
    PUBLIC_FETCH_SLOTS: `${CALENDAR_SERVICES_BASE_URL}/publicFetchSlots`,
  },
  SCHEDULE_SERVICES: {
    SCHEDULE_BOOKING: `${SCHEDULE_SERVICES_BASE_URL}/scheduleBooking`,
    DELETE_SCHEDULE_BOOKING: `${SCHEDULE_SERVICES_BASE_URL}/deleteScheduleBooking`,
    SESSION_WAITLIST: `${SCHEDULE_SERVICES_BASE_URL}/sessionWaitlist`,
    SESSION_DATA: `${SCHEDULE_SERVICES_BASE_URL}/sessionData`,
    AGGREGATED_SESSION_VIEW: `${SCHEDULE_SERVICES_BASE_URL}/aggregatedSessionView`,
    FETCH_MUTUAL_SCHEDULES: `${SCHEDULE_SERVICES_BASE_URL}/fetchMutualSchedules`,
    FETCH_SCHEDULE_BOOKING: `${SCHEDULE_SERVICES_BASE_URL}/fetchScheduleBooking`,
    FETCH_HOST_AND_ATTENDEE_SESSIONS: `${SCHEDULE_SERVICES_BASE_URL}/hostAttendeeSessionView`,
  },
};

export const {
  AUTH_SERVICES,
  CALENDAR_SERVICES,
  KNOWLEDGE_SESSIONS_SERVICES,
  LANDING_PAGE_SERVICES,
  SCHEDULE_SERVICES,
  USER_PROFILE_SERVICES,
} = HIVEPATH_API_URLS;
export default HIVEPATH_API_URLS;
